# Generated by Django 2.1.4 on 2019-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubanId', models.CharField(max_length=20, verbose_name='豆瓣id')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('poster', models.CharField(max_length=255, verbose_name='海报url')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
    ]
