# Generated by Django 2.1.4 on 2019-04-22 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0003_auto_20190422_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actorId', models.CharField(max_length=20, verbose_name='演员id')),
                ('title', models.CharField(max_length=100, verbose_name='演员姓名')),
                ('avatar', models.CharField(max_length=255, verbose_name='演员头像url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏演员',
                'verbose_name_plural': '用户收藏演员',
            },
        ),
        migrations.AlterModelOptions(
            name='userfavormovie',
            options={'verbose_name': '用户收藏电影', 'verbose_name_plural': '用户收藏电影'},
        ),
        migrations.AlterUniqueTogether(
            name='userfavoractor',
            unique_together={('user', 'actorId')},
        ),
    ]
