# Generated by Django 2.1.4 on 2019-04-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20190422_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavoractor',
            old_name='title',
            new_name='name',
        ),
    ]
