# Generated by Django 2.1.4 on 2019-04-26 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0006_userfavorgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorgenre',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='用户'),
        ),
    ]
