# Generated by Django 2.1.4 on 2019-04-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0009_auto_20190427_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoractor',
            name='works',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='相关作品'),
        ),
    ]
