# Generated by Django 2.1.4 on 2019-04-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='doubanIds',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='相关电影'),
        ),
    ]
