# Generated by Django 2.1.4 on 2019-04-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190428_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movidId',
            new_name='movieId',
        ),
    ]
