# Generated by Django 2.1.4 on 2019-04-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190428_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='closest_movie',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='相似电影'),
        ),
    ]
