# Generated by Django 2.1.4 on 2019-04-26 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubanId', models.CharField(max_length=20, verbose_name='豆瓣id')),
                ('description', models.CharField(max_length=255, verbose_name='推荐解释')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '系统推荐',
                'verbose_name_plural': '系统推荐',
            },
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user', 'doubanId')},
        ),
    ]
