# Generated by Django 2.1.4 on 2019-04-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='doubanIds',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='豆瓣ids'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='doubanId',
        ),
    ]
