# Generated by Django 2.1.4 on 2019-04-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20190428_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='random_rank',
            field=models.FloatField(max_length=255, verbose_name='随机排序因子'),
        ),
    ]
